[feature] integration in admin
trilbymedia/grav-plugin-login-oauth2 pull request #8
Opened 2019-03-19 14:14 UTC by olivierdalang

This fixes #7 

It seems to work here, however some styling needs to be done for the button to be properly centered.

2019-03-19 18:28 UTC, rhukster requested changes
Please provide a default entry for `enable_in_admin:` in the `login-oauth2.yaml` file

2019-03-25 11:19 UTC, olivierdalang commented
Ok I made the change and also added a line of css to center the buttons in the admin form.

2019-03-25 15:45 UTC, mahagr approved these changes

2019-03-26 00:19 UTC, merged

2019-03-26 00:19 UTC, rhukster commented
i've merged, will check the styling a bit later to tweak for admin